[opener]
edit = [
	{ run = 'hemux "$@"', block = false },
]

[manager]
ratio = [1,4,4]
show_hidden = true
sort_by = "natural"
sort_dir_first = true
# linemode = "size"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
