
[cursor]
style = "Beam"
unfocused_hollow = true

[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

[font]
size = 12.0
normal.family = "MesloLGS Nerd Font Mono"
# normal.style = "Light"
# bold.style = "SemiBold"
# italic.style = "Italic"
# offset.x = 0
offset.y = 1
# glyph_offset.x = 0
# glyph_offset.y = 0

[mouse]
hide_when_typing = false

[selection]
save_to_clipboard = true

[scrolling]
history = 50000
multiplier = 3

[window]
blur = true
opacity = 0.85
decorations = "Transparent"
dynamic_padding = true
dynamic_title = true
option_as_alt = "Both"
startup_mode = "Windowed"

[window.dimensions]
columns = 170
lines = 50

[window.padding]
x = 5
y = 5

[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]
