theme = "catppuccin_mocha"

[editor]
bufferline = "always"
color-modes = true
true-color = true
cursorline = true
auto-save = true # save when window looses focus
rulers = [120]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spacer", "spinner", "spacer", "version-control"]
center = ["file-base-name", "file-modification-indicator"]
right = ["diagnostics", "workspace-diagnostics", "selections", "position", "file-encoding", "file-line-ending" ]
separator = "│"
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.indent-guides]
render = true

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.whitespace.characters]
tab = "→"

[editor.file-picker]
hidden = false # show hidden files as in starting with a dot
git-global = false # show files hidden by git globally

[keys.normal]
"y" = "yank_joined_to_clipboard"
"Y" = ["extend_to_line_bounds", "yank_joined_to_clipboard"]
"p" = "paste_clipboard_after"

"d" = "delete_selection"
"D" = ["extend_to_line_bounds", "delete_selection"]
"R" = ":clipboard-paste-replace" 

"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
"%" = "match_brackets"

"G" = "goto_last_line"
"H" = "goto_previous_buffer"
"L" = "goto_next_buffer"
"J" = "half_page_down"
"K" = "half_page_up"
"V" = ["extend_to_line_bounds", "select_mode"]

# Search for word under cursor
"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
"#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_prev"]

[keys.select]
"y" = "yank_joined_to_clipboard"
"p" = "paste_clipboard_after"

"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
D = ["extend_to_line_bounds", "delete_selection", "normal_mode"]
C = ["goto_line_start", "extend_to_line_bounds", "change_selection"]
"%" = "match_brackets"

[keys.normal.space]
# Add comma to the end of the line
"," = [
    "save_selection",
    "goto_line_end",
    ":append-output echo ','",
    "collapse_selection",
    "delete_selection",
    "jump_backward",
]
# Add semicolumn to the end of the line
";" = [
    "save_selection",
    "goto_line_end",
    ":append-output echo ';'",
    "collapse_selection",
    "delete_selection",
    "jump_backward",
]
o = ":sh tmux popup"
n = ":sh tmux popup -E 'lf'"
F = "file_picker_in_current_buffer_directory" # useful for accessing sibling files rather than a file tree
"." = ":toggle-option file-picker.git-ignore" # toggle seeing files hidden with the .gitignore in file pickers
"=" = ":format"
"+" = ":indent-style 4"
"q" = ":wqa!" 
"c" = { "r" = ":config-reload", "o" = ":config-open" }

