theme = "catppuccin_mocha"

[editor]
line-number = "relative"
bufferline = "multiple"
color-modes = true
true-color = true
cursorline = true
auto-save = true
rulers = [120]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spacer", "spinner", "spacer", "version-control"]
center = ["file-name", "file-modification-indicator", "read-only-indicator"]
right = ["diagnostics", "workspace-diagnostics", "selections", "register", "position", "file-encoding", "file-line-ending", "file-type" ]
separator = "│"
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"

[editor.lsp]
auto-signature-help = true
display-inlay-hints = true
display-messages = true

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "error"

[editor.indent-guides]
render = true
character = "┊" # Some characters that work well: "▏", "┆", "┊", "╎"

[editor.whitespace.render]
space = "none"
tab = "all"
newline = "none"

[editor.whitespace.characters]
tab = "→"

[editor.file-picker]
hidden = false # show hidden files as in starting with a dot
git-global = false # show files hidden by git globally

# [editor.sticky-context]
# enable = true
# indicator = true
# max-lines = 10

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
"y" = "yank_joined_to_clipboard"
"Y" = ["extend_to_line_bounds", "yank_joined_to_clipboard"]
"p" = "paste_clipboard_after"
"R" = ":clipboard-paste-replace" 

"{" = ["goto_prev_paragraph", "collapse_selection"]
"}" = ["goto_next_paragraph", "collapse_selection"]
0 = "goto_line_start"
"$" = "goto_line_end"

# Move line up/down using A-k, A-j
"A-k" = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before"
]
"A-j" = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_down",
  "paste_before"
]

"V" = ["extend_to_line_bounds", "select_mode"]
"C" = "@vglc" # same as t<CR>c

# Search for word under cursor
"*" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_next"]
"#" = ["move_char_right", "move_prev_word_start", "move_next_word_end", "search_selection", "search_prev"]

[keys.normal."["]
"[" = "goto_previous_buffer"

[keys.normal."]"]
"]" = "goto_next_buffer"

[keys.insert]
# VSCode-like auto-completeion (pretty much all IDEs do it on C-space)
"C-space" = "completion"

[keys.select]
"y" = "yank_joined_to_clipboard"
"p" = "paste_clipboard_after"

"{" = ["extend_to_line_bounds", "goto_prev_paragraph"]
"}" = ["extend_to_line_bounds", "goto_next_paragraph"]
0 = "goto_line_start"
"$" = "goto_line_end"

[keys.normal.space]
t = ":sh tmux popup"
e = ":sh tmux splitw -bh -l30% yazi"
E = ":sh tmux popup -E yazi"
F = "file_picker_in_current_buffer_directory" # useful for accessing sibling files rather than a file tree
l = ":toggle lsp.display-inlay-hints"
"." = ":toggle-option file-picker.git-ignore" # toggle seeing files hidden with the .gitignore in file pickers
"=" = ":format"
"q" = ":wqa!" 
"c" = { "r" = ":config-reload", "o" = ":config-open" }

